import type { Course } from "@/types/course";

export const FEATURED = "Featured";

export const skillCategories = [
  FEATURED,
  "Music",
  "Drawing & Painting",
  "Marketing",
  "Animation",
  "Social Media",
  "UI/UX Design",
  "Creative Marketing",
  "Digital Illustration",
  "Film & Video",
  "Crafts",
  "Freelance & Entrepreneurship",
  "Graphic Design",
  "Photography",
  "Productivity",
  "Web Development",
  "Data Science",
  "Cooking",
];

export const moreSkillCategories = ["Business", "Finance", "Fitness", "Writing"];

export const courses: Course[] = [
  {
    id: 1,
    title: "Learn Figma from Basic",
    category: "UI/UX Design",
    image: "/assets/images/temp/product-1.jpg",
    author: "purepearl studio",
    rating: 4.5,
    lessons: 24,
    duration: "3 hours 10 mins",
    comments: 72,
    level: "Beginner",
    students: 41,
    price: 25,
    featured: true,
  },
  {
    id: 2,
    title: "Build Digital Asset",
    category: "Web Development",
    image: "/assets/images/temp/product-2.jpg",
    author: "northwave labs",
    rating: 4.5,
    lessons: 18,
    duration: "2 hours 45 mins",
    comments: 54,
    level: "Intermediate",
    students: 33,
    price: 25,
    featured: true,
  },
  {
    id: 3,
    title: "The Power of Big Data",
    category: "Data Science",
    image: "/assets/images/temp/product-3.jpg",
    author: "datavista academy",
    rating: 4.5,
    lessons: 21,
    duration: "3 hours 55 mins",
    comments: 88,
    level: "Advanced",
    students: 57,
    price: 25,
    featured: true,
  },
  {
    id: 4,
    title: "Balancing Productivity and Life",
    category: "Productivity",
    image: "/assets/images/temp/product-4.jpg",
    author: "purepearl studio",
    rating: 4.5,
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    level: "Beginner",
    students: 26,
    price: 25,
    featured: true,
  },
  {
    id: 5,
    title: "Mastering Money Management",
    category: "Finance",
    image: "/assets/images/temp/product-5.jpg",
    author: "wealthwise co",
    rating: 4.5,
    lessons: 15,
    duration: "1 hour 48 mins",
    comments: 43,
    level: "Beginner",
    students: 38,
    price: 25,
    featured: true,
  },
  {
    id: 6,
    title: "From Idea to Startup Success",
    category: "Freelance & Entrepreneurship",
    image: "/assets/images/temp/product-6.jpg",
    author: "foundry collective",
    rating: 4.5,
    lessons: 26,
    duration: "4 hours 05 mins",
    comments: 96,
    level: "Intermediate",
    students: 64,
    price: 25,
    featured: true,
  },
  {
    id: 7,
    title: "Music Production Masterclass",
    category: "Music",
    image: "/assets/images/temp/product-5.jpg",
    author: "beatforge studio",
    rating: 4.5,
    lessons: 20,
    duration: "3 hours 30 mins",
    comments: 61,
    level: "Intermediate",
    students: 45,
    price: 25,
  },
  {
    id: 8,
    title: "Drawing & Painting for Beginners",
    category: "Drawing & Painting",
    image: "/assets/images/temp/product-1.jpg",
    author: "artnest studio",
    rating: 4.5,
    lessons: 14,
    duration: "1 hour 55 mins",
    comments: 37,
    level: "Beginner",
    students: 29,
    price: 25,
  },
  {
    id: 9,
    title: "Digital Marketing Fundamentals",
    category: "Marketing",
    image: "/assets/images/temp/product-3.jpg",
    author: "growthpixel agency",
    rating: 4.5,
    lessons: 22,
    duration: "3 hours 12 mins",
    comments: 74,
    level: "Beginner",
    students: 52,
    price: 29,
  },
  {
    id: 10,
    title: "Animation Essentials with After Effects",
    category: "Animation",
    image: "/assets/images/temp/product-6.jpg",
    author: "motionmint studio",
    rating: 4.5,
    lessons: 19,
    duration: "2 hours 58 mins",
    comments: 48,
    level: "Intermediate",
    students: 35,
    price: 25,
  },
  {
    id: 11,
    title: "Social Media Growth Strategy",
    category: "Social Media",
    image: "/assets/images/temp/product-2.jpg",
    author: "trendloop media",
    rating: 4.8,
    lessons: 16,
    duration: "1 hour 40 mins",
    comments: 66,
    level: "Beginner",
    students: 47,
    price: 25,
  },
  {
    id: 12,
    title: "Creative Marketing That Converts",
    category: "Creative Marketing",
    image: "/assets/images/temp/product-3.jpg",
    author: "growthpixel agency",
    rating: 4.5,
    lessons: 23,
    duration: "3 hours 24 mins",
    comments: 51,
    level: "Intermediate",
    students: 30,
    price: 25,
  },
  {
    id: 13,
    title: "Digital Illustration Essentials",
    category: "Digital Illustration",
    image: "/assets/images/temp/product-1.jpg",
    author: "artnest studio",
    rating: 4.7,
    lessons: 18,
    duration: "2 hours 35 mins",
    comments: 44,
    level: "Beginner",
    students: 39,
    price: 25,
  },
  {
    id: 14,
    title: "Video Editing Bootcamp",
    category: "Film & Video",
    image: "/assets/images/temp/product-6.jpg",
    author: "framecraft labs",
    rating: 4.5,
    lessons: 28,
    duration: "4 hours 45 mins",
    comments: 83,
    level: "Advanced",
    students: 61,
    price: 35,
  },
  {
    id: 15,
    title: "Handmade Crafts Workshop",
    category: "Crafts",
    image: "/assets/images/temp/product-4.jpg",
    author: "craftloft studio",
    rating: 4.5,
    lessons: 12,
    duration: "1 hour 30 mins",
    comments: 28,
    level: "Beginner",
    students: 22,
    price: 25,
  },
  {
    id: 16,
    title: "Graphic Design Masterclass",
    category: "Graphic Design",
    image: "/assets/images/temp/product-1.jpg",
    author: "purepearl studio",
    rating: 4.5,
    lessons: 32,
    duration: "5 hours 15 mins",
    comments: 104,
    level: "Intermediate",
    students: 70,
    price: 25,
  },
  {
    id: 17,
    title: "Photography Lighting Techniques",
    category: "Photography",
    image: "/assets/images/temp/product-4.jpg",
    author: "lightbox collective",
    rating: 4.9,
    lessons: 15,
    duration: "2 hours 05 mins",
    comments: 47,
    level: "Intermediate",
    students: 36,
    price: 25,
  },
  {
    id: 18,
    title: "Cooking Mastery at Home",
    category: "Cooking",
    image: "/assets/images/temp/product-5.jpg",
    author: "flavorfield kitchen",
    rating: 4.5,
    lessons: 20,
    duration: "2 hours 40 mins",
    comments: 58,
    level: "Beginner",
    students: 43,
    price: 25,
  },
  {
    id: 19,
    title: "Business Strategy Foundations",
    category: "Business",
    image: "/assets/images/temp/product-3.jpg",
    author: "foundry collective",
    rating: 4.5,
    lessons: 25,
    duration: "3 hours 48 mins",
    comments: 69,
    level: "Advanced",
    students: 54,
    price: 39,
  },
  {
    id: 20,
    title: "Fitness for Busy People",
    category: "Fitness",
    image: "/assets/images/temp/product-6.jpg",
    author: "vitalcore coaching",
    rating: 4.5,
    lessons: 13,
    duration: "1 hour 25 mins",
    comments: 34,
    level: "Beginner",
    students: 48,
    price: 25,
  },
  {
    id: 21,
    title: "Content Writing That Sells",
    category: "Writing",
    image: "/assets/images/temp/product-2.jpg",
    author: "inkwell studio",
    rating: 4.5,
    lessons: 16,
    duration: "2 hours 12 mins",
    comments: 40,
    level: "Beginner",
    students: 31,
    price: 25,
  },
];
